# Checkov
# AnÃ¡lisis de archivos Dockerfile
# 

trigger:
- master

resources:
- repo: self

variables:
  dockerRegistryServiceConnection: '26a65500-b05f-4a4c-a7dd-73a9e7a59dcb'
  imageRepository: 'malevarrokart'
  containerRegistryn: 'myacr21942.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'
  vmImageName: 'ubuntu-latest'
  sariflog: 'ImageAnalysisLogs'

pool:
  vmImage: $(vmImageName)

stages:
  - stage: CodeSecurityScan
    displayName: Code Security Scan
    jobs:
      - job: Checkov
        displayName: Checkov
        pool:
          vmImage: $(vmImageName)
        steps:
        - task: Bash@3
          displayName: 'Install Checkov CLI'
          inputs:
            targetType: 'inline'
            script: |
              echo 'Install Checkov'
              pip3 install checkov
              mkdir checkov-report
        - task: Bash@3
          displayName: 'Checkov Dockerfile Analysis'
          inputs:
            targetType: 'inline'
            script: |
              checkov -d . --soft-fail --framework all --output junitxml > ./checkov-report/TEST-checkov-IaC-report.xml
        - task: Bash@3
          displayName: 'Checkov SCA Analysis'
          inputs:
            targetType: 'inline'
            script: |
              checkov -d . --soft-fail --framework sca_package --bc-api-key $(API) --output junitxml > ./checkov-report/TEST-checkov-SCA-report.xml
        - task: Docker@2
          inputs:
            containerRegistry: 'myacr21942'
            command: 'login'
        - task: Bash@3
          displayName: 'Checkov SCA Image Analysis'
          inputs:
            targetType: 'inline'
            script: |
              checkov -d . --soft-fail --framework sca_image --bc-api-key --bc-api-key $(API)
              #--output junitxml > ./checkov-report/TEST-checkov-full-report.xml
        - task: Bash@3
          displayName: 'Checkov Full Analysis'
          inputs:
            targetType: 'inline'
            script: |
              checkov --docker-image $(imageRepository) --dockerfile-path $(dockerfilePath) --soft-fail --bc-api-key $(API)
              #--output junitxml > ./checkov-report/TEST-checkov-full-report.xml
        - task: PublishTestResults@2
          displayName: 'Checkov Dockerfile Report'
          inputs:
            testResultsFormat: 'JUnit'
            testResultsFiles: '**/TEST-checkov-IaC-report.xml'
            searchFolder: '$(System.DefaultWorkingDirectory)/checkov-report'
            mergeTestResults: true
            testRunTitle: 'Checkov Dockerfile Report'
            failTaskOnFailedTests: false
            publishRunAttachments: true
        - task: PublishTestResults@2
          displayName: 'Checkov SCA Report'
          inputs:
            testResultsFormat: 'JUnit'
            testResultsFiles: '**/TEST-checkov-SCA-report.xml'
            searchFolder: '$(System.DefaultWorkingDirectory)/checkov-report'
            mergeTestResults: true
            testRunTitle: 'Checkov SCA Report'
            failTaskOnFailedTests: false
            publishRunAttachments: true